#!/bin/bash

source ./configs/zsh/.zshenv

big_message "🧩 Configuration wizard"

OPTIONS=(
    "zsh"
    "zhs_plugins"
    "git"
    "ghostty"
    "nvim"
    "ideavim"
    "bat"
    "powerline_fonts"
    "hushlogin"
    "claude"
    )

SELECTED=$(selection "🧩 Select configs to apply" "${OPTIONS[@]}")

if [[ -z "$SELECTED" ]]; then
    big_message "👍 Nothing selected"
    exit 0
fi

if [[ $SELECTED == *"zsh"* ]]; then
    mkdir -p $HOME/.oh-my-zsh/custom/themes

    ln -sf $DOT_CONFIGS_DIR/zsh/.zshenv $HOME/.zshenv
    ln -sf $DOT_CONFIGS_DIR/zsh/janis.zsh-theme $HOME/.oh-my-zsh/custom/themes/janis.zsh-theme
    ln -sf $DOT_CONFIGS_DIR/zsh/.zshrc $HOME/.zshrc

    if [[ ! -f $HOME/.zshenv_private ]]; then
        cp $DOT_FILES_DIR/extra/.zshenv_private.example $HOME/.zshenv_private

        big_message "👍  Created empty ~/.zshenv_private file. Please fill it with your private environment variables."
    else
        big_message "⚠️ ~/.zshenv_private already exists, skipping"
    fi

    big_message "👍 Zsh configuration applied"
fi

if [[ $SELECTED == *"zsh_plugins"* ]]; then
    show_spinner "zsh-autosuggestions" git clone --depth 1 --quiet https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-autosuggestions 2> /dev/null
    show_spinner "zsh-syntax-highlighting" git clone --depth 1 --quiet https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting 2> /dev/null
    show_spinner "zsh-bat" git clone --depth 1 --quiet https://github.com/fdellwing/zsh-bat.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-bat 2> /dev/null
    show_spinner "zsh-256color" git clone --depth 1 --quiet https://github.com/chrissicool/zsh-256color ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-256color 2> /dev/null
    show_spinner "zsh-artisan" git clone --depth 1 --quiet https://github.com/jessarcher/zsh-artisan.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/artisan 2> /dev/null
    show_spinner "fzf-tab" git clone --depth 1 --quiet https://github.com/Aloxaf/fzf-tab ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/fzf-tab 2> /dev/null

    big_message "👍 Zsh plugins installed"
fi

if [[ $SELECTED == *"git"* ]]; then
    ln -sf $DOT_CONFIGS_DIR/git/.gitconfig $HOME/.gitconfig
    ln -sf $DOT_CONFIGS_DIR/git/.gitignore_global $HOME/.gitignore_global

    big_message "👍 Git configuration applied"
fi

if [[ $SELECTED == *"ghostty"* ]]; then
    ln -sf $DOT_CONFIGS_DIR/ghostty $HOME/.config/ghostty

    big_message "👍 Ghostty configuration applied"
fi

if [[ $SELECTED == *"nvim"* ]]; then
    rm -rf $HOME/.config/nvim
    ln -sf $DOT_CONFIGS_DIR/nvim $HOME/.config/nvim

    big_message "👍 Neovim configuration applied"
fi

if [[ $SELECTED == *"ideavim"* ]]; then
    ln -sf $DOT_CONFIGS_DIR/ideavim/.ideavimrc $HOME/.ideavimrc

    big_message "👍 IdeaVim configuration applied"
fi

if [[ $SELECTED == *"bat"* ]]; then
    mkdir -p $HOME/.config/bat
    ln -sf $DOT_CONFIGS_DIR/bat/config $HOME/.config/bat/config

    big_message "👍 Bat configuration applied"
fi

if [[ $SELECTED == *"claude"* ]]; then
    ln -sf $DOT_FILES_DIR/configs/claude/settings.json $HOME/.claude/settings.json

    big_message "👍 Claude configuration applied"
fi

if [[ $SELECTED == *"powerline_fonts"* ]]; then
    git clone --depth 1 --quiet https://github.com/powerline/fonts.git $HOME/dot-files/fonts/powerline_fonts 2> /dev/null

    big_message "👍 Powerline fonts installed"
fi

if [[ $SELECTED == *"hushlogin"* ]]; then
    ln -sf $DOT_FILES_DIR/extra/.hushlogin $HOME/.hushlogin

    big_message "👍 Hushlogin applied"
fi

cd $DOT_FILES_DIR
big_message "✅ Done"
