### CONFIG ###

# UTF-8 default
set-window-option -g utf8 on

# Status bar on top
set -g status-position bottom

# Enable mouse
set -g mouse on

# Auto rename
setw -g automatic-rename on

# Fix scrollbar
set -ga terminal-overrides ',xterm*:smcup@:rmcup@'

# Increase scroll-back history
set -g history-limit 5000

# Use 256 colors
set -g default-terminal "screen-256color"

# Start windows from number 1
set -g base-index 1
set -g pane-base-index 1

# Increase VIM responsiveness
set -sg escape-tim 1

# Increate repeat time for repeatable commands
set -g repeat-time 1000

# Window flash on change
setw -g monitor-activity on
set -g visual-activity on

# Renumber windows on close
set -g renumber-windows on

### STATUS BAR ###

# Use UTF-8 in status bar
set -g status-utf8 on

# Status bar refresh interval
set -g status-interval 2

set -g status-justify "left"
set -g status "on"
set -g status-left-style "none"
set -g message-command-style "fg=colour144,bg=colour237"
set -g status-right-style "none"
set -g pane-active-border-style "fg=colour27"
set -g status-utf8 "on"
set -g status-style "bg=colour15,none"
set -g message-style "fg=colour144,bg=colour237"
set -g pane-border-style "fg=colour237"
set -g status-right-length "100"
set -g status-left-length "100"
setw -g window-status-activity-attr "none"
setw -g window-status-activity-style "fg=colour27,bg=colour234,none"
setw -g window-status-separator ""
setw -g window-status-style "fg=colour39,bg=colour234,none"
set -g status-left "#[fg=white,bg=colour63] #S #[fg=colour63,bg=colour234,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=colour237,bg=colour234,nobold,nounderscore,noitalics]#[fg=colour144,bg=colour237] #(~/dot-files/scripts/spotify-current.sh) #[fg=colour144,bg=colour237] %d.%m.%Y  %H:%M #[fg=colour63,bg=colour237,nobold,nounderscore,noitalics]#[fg=colour15,bg=colour63] #h "
setw -g window-status-format "#[fg=colour144,bg=colour234] #I #[fg=colour144,bg=colour234] #W "
setw -g window-status-current-format "#[fg=colour234,bg=colour63,nobold,nounderscore,noitalics]#[fg=black,bg=colour63] #I #[fg=black,bg=colour63] #W #[fg=colour63,bg=colour234,nobold,nounderscore,noitalics]"

# Spotify in status bar


### KEY BINDINGS###
set -g prefix C-a
bind C-a send-prefix
unbind C-b

# command prefix
set -g prefix C-a

# start window indexing at one instead of zero
set -g base-index 1

unbind % # remove default binding since replacing
bind v split-window -h
bind h split-window -v
bind R source-file ~/.tmux.conf \; display-message "Config reloaded..."

source blabla.conf
