#!/bin/bash

OPTIONS=(
    "php@8.4"
    "php-intl"
    "composer"
    "mysql"
    "node"
    "sqlite"
    "python"
    "go"
    "bun"
    "icu4c"
    "redis"
    "awscli"
)

SELECTED=$(selection "💻 Select dev tools to install" "${OPTIONS[@]}")

if [[ -z "$SELECTED" ]]; then
    big_message "👍 No dev tools selected"
    exit 0
fi

for SELECTION in $SELECTED; do
    brew_install "$SELECTION"
done

big_message "✅ Done."
