#!/bin/bash

OPTIONS=(
    "git"
    "gh"
    "lazygit"
    "watch"
    "curl"
    "wget"
    "tree"
    "font-monaspace"
    "exiftool"
    "zplug"
    "ripgrep"
    "fzf"
    "neovim"
    "btop"
    "bat"
    "eza"
    "jless"
    "jq"
    "ffmpeg"
    "gum"
    "tmux"
    "tldr"
)

SELECTED=$(selection "🛠️ Select tools to install" "${OPTIONS[@]}")

if [[ -z "$SELECTED" ]]; then
    big_message "👍 No tools selected"
    exit 0
fi

for SELECTION in $SELECTED; do
    brew_install "$SELECTION"
done

big_message "✅ Done."
