#!/bin/bash

OPTIONS=(
    aerospace
    jankyborders
)

SELECTED=$(selection "🧩 UI customization tools" "${OPTIONS[@]}")

if [[ -z "$SELECTED" ]]; then
    big_message "👍 Nothing selected"
    exit 0
fi

if [[ "$SELECTED" == "aerospace" ]]; then
    brew_install_cask "nikitabobko/tap/aerospace"
fi

if [[ "$SELECTED" == "jankyborders" ]]; then
    brew_install "FelixKratz/formulae/borders"
fi

big_message "✅ Done."

