#!/bin/bash


# ANSI color names 0–15
names=(
  "Black"
  "Red"
  "Green"
  "Yellow"
  "Blue"
  "Magenta"
  "Cyan"
  "White"
  "Bright Black"
  "Bright Red"
  "Bright Green"
  "Bright Yellow"
  "Bright Blue"
  "Bright Magenta"
  "Bright Cyan"
  "Bright White"
)

for i in "${!names[@]}"; do
  # colored block as background
  printf "\e[48;5;%sm  \e[0m " "$i"
  # colored text showing index and name
  printf "\e[38;5;%sm%2d: %s\e[0m\n" "$i" "$i" "${names[$i]}"
done
