#! /bin/bash

${SALTZ_DIR}/artisan route:list --json | jq -r '.[] | "\(.uri)\t\(.name)"' |  fzf --prompt="" --no-separator --input-border=rounded --info=hidden --cycle --no-scrollbar --list-border=rounded 

# ${SALTZ_DIR}/artisan route:list | fzf
